export type Suit = "wands" | "cups" | "swords" | "pentacles";
export type Arcana = "major" | "minor";
export type YesNo = "Yes" | "No" | "Maybe";

export type TarotCard = {
  id: string;
  name: string;
  arcana: Arcana;
  suit: Suit | null;
  index: string;
  pip: number;
  court: boolean;
  blurb: string;
  upright: string;
  reversed: string;
  yesNo: YesNo;
};

export const DECK: readonly TarotCard[] = [
  {
    "id": "the-fool",
    "name": "The Fool",
    "blurb": "New beginnings, innocence, and the courage to step into the unknown. The Fool starts every journey with nothing but faith.",
    "upright": "new beginnings, innocence, spontaneity, free spirit, adventure",
    "reversed": "recklessness, risk-taking, holding back, fear of the unknown, naivety",
    "yesNo": "Yes",
    "arcana": "major",
    "suit": null,
    "index": "0",
    "pip": 0,
    "court": false
  },
  {
    "id": "the-magician",
    "name": "The Magician",
    "blurb": "Willpower, skill, and the ability to manifest your desires. The Magician reminds you that you already have every tool you need.",
    "upright": "willpower, skill, manifestation, resourcefulness, power",
    "reversed": "manipulation, poor planning, untapped potential, trickery",
    "yesNo": "Yes",
    "arcana": "major",
    "suit": null,
    "index": "I",
    "pip": 1,
    "court": false
  },
  {
    "id": "the-high-priestess",
    "name": "The High Priestess",
    "blurb": "Intuition, mystery, and the wisdom of the subconscious. The High Priestess asks you to trust what you feel but cannot yet prove.",
    "upright": "intuition, mystery, subconscious, inner knowledge, divine feminine",
    "reversed": "secrets, disconnected from intuition, withdrawal, repressed feelings",
    "yesNo": "Maybe",
    "arcana": "major",
    "suit": null,
    "index": "II",
    "pip": 2,
    "court": false
  },
  {
    "id": "the-empress",
    "name": "The Empress",
    "blurb": "Abundance, nurturing, and creative fertility. The Empress represents growth that comes from caring for something with patience.",
    "upright": "fertility, abundance, nurturing, beauty, nature",
    "reversed": "dependence, creative block, smothering, neglect",
    "yesNo": "Yes",
    "arcana": "major",
    "suit": null,
    "index": "III",
    "pip": 3,
    "court": false
  },
  {
    "id": "the-emperor",
    "name": "The Emperor",
    "blurb": "Authority, structure, and the discipline to build something lasting. The Emperor provides stability through clear boundaries.",
    "upright": "authority, structure, stability, leadership, father figure",
    "reversed": "domination, rigidity, inflexibility, loss of control, tyranny",
    "yesNo": "Yes",
    "arcana": "major",
    "suit": null,
    "index": "IV",
    "pip": 4,
    "court": false
  },
  {
    "id": "the-hierophant",
    "name": "The Hierophant",
    "blurb": "Tradition, spiritual guidance, and the wisdom found within established systems. The Hierophant points to a teacher or a teaching.",
    "upright": "tradition, conformity, morality, spiritual guidance, institutions",
    "reversed": "rebellion, subversiveness, challenging convention, personal beliefs",
    "yesNo": "Maybe",
    "arcana": "major",
    "suit": null,
    "index": "V",
    "pip": 5,
    "court": false
  },
  {
    "id": "the-lovers",
    "name": "The Lovers",
    "blurb": "Love, union, and meaningful choices. The Lovers card signals a relationship or decision that aligns head and heart.",
    "upright": "love, union, alignment, choices, harmony",
    "reversed": "disharmony, imbalance, misalignment, bad choices, separation",
    "yesNo": "Yes",
    "arcana": "major",
    "suit": null,
    "index": "VI",
    "pip": 6,
    "court": false
  },
  {
    "id": "the-chariot",
    "name": "The Chariot",
    "blurb": "Determination, willpower, and forward momentum. The Chariot says you can overcome obstacles through focused control.",
    "upright": "determination, control, victory, willpower, momentum",
    "reversed": "lack of control, aggression, defeat, obstacles, self-doubt",
    "yesNo": "Yes",
    "arcana": "major",
    "suit": null,
    "index": "VII",
    "pip": 7,
    "court": false
  },
  {
    "id": "strength",
    "name": "Strength",
    "blurb": "Inner strength, courage, and quiet power. Strength is not force -- it is the patience to tame what is wild within you.",
    "upright": "inner strength, courage, patience, compassion, influence",
    "reversed": "self-doubt, weakness, insecurity, cowardice, raw emotion",
    "yesNo": "Yes",
    "arcana": "major",
    "suit": null,
    "index": "VIII",
    "pip": 8,
    "court": false
  },
  {
    "id": "the-hermit",
    "name": "The Hermit",
    "blurb": "Soul-searching, solitude, and inner guidance. The Hermit withdraws not to escape, but to find a truth only silence reveals.",
    "upright": "soul-searching, introspection, solitude, inner guidance, contemplation",
    "reversed": "isolation, loneliness, withdrawal, losing your way, anti-social",
    "yesNo": "Maybe",
    "arcana": "major",
    "suit": null,
    "index": "IX",
    "pip": 9,
    "court": false
  },
  {
    "id": "wheel-of-fortune",
    "name": "Wheel of Fortune",
    "blurb": "Fate, cycles, and turning points beyond your control. The Wheel reminds you that nothing stays the same forever.",
    "upright": "luck, fate, cycles, destiny, turning point",
    "reversed": "bad luck, resistance to change, breaking cycles, external forces",
    "yesNo": "Maybe",
    "arcana": "major",
    "suit": null,
    "index": "X",
    "pip": 10,
    "court": false
  },
  {
    "id": "justice",
    "name": "Justice",
    "blurb": "Fairness, truth, and the consequences of your actions. Justice says the outcome will reflect what was actually earned.",
    "upright": "fairness, truth, cause and effect, law, accountability",
    "reversed": "injustice, dishonesty, lack of accountability, unfair treatment",
    "yesNo": "Maybe",
    "arcana": "major",
    "suit": null,
    "index": "XI",
    "pip": 11,
    "court": false
  },
  {
    "id": "the-hanged-man",
    "name": "The Hanged Man",
    "blurb": "Surrender, new perspective, and willing sacrifice. The Hanged Man finds clarity by letting go of the need to act.",
    "upright": "suspension, letting go, new perspective, sacrifice, pause",
    "reversed": "stalling, needless sacrifice, fear of sacrifice, delays, resistance",
    "yesNo": "No",
    "arcana": "major",
    "suit": null,
    "index": "XII",
    "pip": 12,
    "court": false
  },
  {
    "id": "death",
    "name": "Death",
    "blurb": "Endings, transformation, and the clearing away of what no longer serves you. Death closes one chapter so another can begin.",
    "upright": "endings, transformation, transition, change, letting go",
    "reversed": "resistance to change, stagnation, inability to move on, fear of endings",
    "yesNo": "No",
    "arcana": "major",
    "suit": null,
    "index": "XIII",
    "pip": 13,
    "court": false
  },
  {
    "id": "temperance",
    "name": "Temperance",
    "blurb": "Balance, moderation, and the patience to blend opposites into something whole. Temperance finds the middle path.",
    "upright": "balance, moderation, patience, purpose, middle path",
    "reversed": "imbalance, excess, self-healing, realignment needed, extremes",
    "yesNo": "Yes",
    "arcana": "major",
    "suit": null,
    "index": "XIV",
    "pip": 14,
    "court": false
  },
  {
    "id": "the-devil",
    "name": "The Devil",
    "blurb": "Bondage, addiction, and the shadow patterns that keep you stuck. The Devil reveals chains you have the power to remove.",
    "upright": "bondage, addiction, materialism, shadow self, dependency",
    "reversed": "releasing limitations, exploring dark thoughts, freedom, reclaiming power",
    "yesNo": "No",
    "arcana": "major",
    "suit": null,
    "index": "XV",
    "pip": 15,
    "court": false
  },
  {
    "id": "the-tower",
    "name": "The Tower",
    "blurb": "Sudden upheaval, revelation, and the collapse of what was built on shaky ground. The Tower destroys to make room for truth.",
    "upright": "sudden change, upheaval, chaos, revelation, disruption",
    "reversed": "avoiding disaster, fear of change, averting crisis, delayed collapse",
    "yesNo": "No",
    "arcana": "major",
    "suit": null,
    "index": "XVI",
    "pip": 16,
    "court": false
  },
  {
    "id": "the-star",
    "name": "The Star",
    "blurb": "Hope, renewal, and quiet faith after a storm. The Star promises healing and reminds you why you started.",
    "upright": "hope, faith, renewal, serenity, inspiration",
    "reversed": "hopelessness, despair, lack of faith, disconnection, creative block",
    "yesNo": "Yes",
    "arcana": "major",
    "suit": null,
    "index": "XVII",
    "pip": 17,
    "court": false
  },
  {
    "id": "the-moon",
    "name": "The Moon",
    "blurb": "Illusion, fear, and the confusion of things half-seen. The Moon asks you to navigate uncertainty without forcing clarity.",
    "upright": "illusion, fear, subconscious, anxiety, confusion",
    "reversed": "releasing fear, repressed emotions, inner confusion, clarity emerging",
    "yesNo": "Maybe",
    "arcana": "major",
    "suit": null,
    "index": "XVIII",
    "pip": 18,
    "court": false
  },
  {
    "id": "the-sun",
    "name": "The Sun",
    "blurb": "Joy, success, and the warmth of things finally going right. The Sun is the brightest card in the deck for good reason.",
    "upright": "positivity, success, joy, vitality, optimism",
    "reversed": "blocked happiness, inner child issues, negativity, sadness",
    "yesNo": "Yes",
    "arcana": "major",
    "suit": null,
    "index": "XIX",
    "pip": 19,
    "court": false
  },
  {
    "id": "judgement",
    "name": "Judgement",
    "blurb": "Reflection, reckoning, and the call to rise into the person you are meant to become. Judgement asks: are you living your truth?",
    "upright": "reflection, reckoning, awakening, absolution, self-evaluation",
    "reversed": "self-doubt, refusal of self-examination, inner critic, ignoring the call",
    "yesNo": "Maybe",
    "arcana": "major",
    "suit": null,
    "index": "XX",
    "pip": 20,
    "court": false
  },
  {
    "id": "the-world",
    "name": "The World",
    "blurb": "Completion, accomplishment, and the wholeness that comes from finishing a full cycle. The World celebrates everything you have become.",
    "upright": "completion, integration, accomplishment, wholeness, travel",
    "reversed": "incompleteness, shortcuts, seeking closure, unfinished business",
    "yesNo": "Yes",
    "arcana": "major",
    "suit": null,
    "index": "XXI",
    "pip": 21,
    "court": false
  },
  {
    "id": "ace-of-wands",
    "name": "Ace of Wands",
    "blurb": "A spark of inspiration and the beginning of a new creative venture. The Ace of Wands says the energy is there -- act on it.",
    "upright": "inspiration, new beginnings, creativity, enthusiasm, potential",
    "reversed": "lack of direction, delays, creative blocks, distractions, procrastination",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "wands",
    "index": "A",
    "pip": 1,
    "court": false
  },
  {
    "id": "two-of-wands",
    "name": "Two of Wands",
    "blurb": "Planning, future vision, and the courage to choose a direction. The Two of Wands stands at the edge of something bigger.",
    "upright": "planning, making decisions, looking ahead, future goals, expansion",
    "reversed": "fear of change, playing small, bad planning, overextension",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "wands",
    "index": "2",
    "pip": 2,
    "court": false
  },
  {
    "id": "three-of-wands",
    "name": "Three of Wands",
    "blurb": "Progress and expansion as early plans begin to take shape. The Three of Wands watches the horizon, knowing results are coming.",
    "upright": "progress, foresight, expansion, looking ahead, enterprise",
    "reversed": "playing small, lack of foresight, obstacles to travel, unexpected delays",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "wands",
    "index": "3",
    "pip": 3,
    "court": false
  },
  {
    "id": "four-of-wands",
    "name": "Four of Wands",
    "blurb": "Celebration, community, and the joy of reaching a milestone. The Four of Wands marks a moment worth pausing to enjoy.",
    "upright": "celebration, home, harmony, community, milestones",
    "reversed": "breakdown in home life, lack of community, instability, conflict at home",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "wands",
    "index": "4",
    "pip": 4,
    "court": false
  },
  {
    "id": "five-of-wands",
    "name": "Five of Wands",
    "blurb": "Conflict, competition, and the chaos of too many voices. The Five of Wands challenges you to fight for what matters.",
    "upright": "conflict, competition, disagreements, struggle, chaos",
    "reversed": "avoiding conflict, inner conflict, suppressed aggression, resolution",
    "yesNo": "Maybe",
    "arcana": "minor",
    "suit": "wands",
    "index": "5",
    "pip": 5,
    "court": false
  },
  {
    "id": "six-of-wands",
    "name": "Six of Wands",
    "blurb": "Victory, recognition, and the pride of a hard-won success. The Six of Wands says your effort is finally being seen.",
    "upright": "success, public recognition, progress, victory, achievement",
    "reversed": "egotism, no confidence, fall from grace, private achievement",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "wands",
    "index": "6",
    "pip": 6,
    "court": false
  },
  {
    "id": "seven-of-wands",
    "name": "Seven of Wands",
    "blurb": "Perseverance and standing your ground when challenged. The Seven of Wands says hold firm -- your position is worth defending.",
    "upright": "perseverance, defiance, standing firm, protectiveness, holding ground",
    "reversed": "giving up, overwhelmed, overly protective, exhaustion, backing down",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "wands",
    "index": "7",
    "pip": 7,
    "court": false
  },
  {
    "id": "eight-of-wands",
    "name": "Eight of Wands",
    "blurb": "Speed, momentum, and things moving quickly. The Eight of Wands says events are accelerating -- stay focused.",
    "upright": "speed, action, quick decisions, air travel, movement",
    "reversed": "delays, frustration, poor timing, chaos, resisting change",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "wands",
    "index": "8",
    "pip": 8,
    "court": false
  },
  {
    "id": "nine-of-wands",
    "name": "Nine of Wands",
    "blurb": "Resilience and the determination to keep going despite exhaustion. The Nine of Wands says you are closer than you think.",
    "upright": "resilience, courage, persistence, test of faith, boundaries",
    "reversed": "stubbornness, inflexibility, refusing to compromise, giving up",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "wands",
    "index": "9",
    "pip": 9,
    "court": false
  },
  {
    "id": "ten-of-wands",
    "name": "Ten of Wands",
    "blurb": "Burden, overcommitment, and the weight of carrying too much. The Ten of Wands asks what you can set down.",
    "upright": "burden, extra responsibility, hard work, completion, overload",
    "reversed": "doing it all alone, collapse, over-commitment, resentment, delegation",
    "yesNo": "No",
    "arcana": "minor",
    "suit": "wands",
    "index": "10",
    "pip": 10,
    "court": false
  },
  {
    "id": "page-of-wands",
    "name": "Page of Wands",
    "blurb": "Curiosity, enthusiasm, and the excitement of exploring something new. The Page of Wands has the spark but not yet the plan.",
    "upright": "exploration, enthusiasm, discovery, free spirit, creative beginnings",
    "reversed": "lack of direction, procrastination, pessimism, hasty starts",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "wands",
    "index": "P",
    "pip": 11,
    "court": true
  },
  {
    "id": "knight-of-wands",
    "name": "Knight of Wands",
    "blurb": "Passion, adventure, and bold action. The Knight of Wands charges forward with contagious energy and little patience for caution.",
    "upright": "energy, passion, lust, action, adventure",
    "reversed": "haste, impulsive, scattered energy, delays, frustration",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "wands",
    "index": "Kn",
    "pip": 12,
    "court": true
  },
  {
    "id": "queen-of-wands",
    "name": "Queen of Wands",
    "blurb": "Confidence, warmth, and magnetic determination. The Queen of Wands leads by inspiring others with her own fire.",
    "upright": "courage, confidence, determination, fiery, magnetic",
    "reversed": "demanding, jealousy, insecure, dependent, controlling",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "wands",
    "index": "Q",
    "pip": 13,
    "court": true
  },
  {
    "id": "king-of-wands",
    "name": "King of Wands",
    "blurb": "Bold leadership, vision, and the honor of someone who leads by example. The King of Wands turns ideas into empires.",
    "upright": "natural leader, vision, entrepreneur, honor, bold",
    "reversed": "impulsive, overbearing, unachievable expectations, tyrannical",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "wands",
    "index": "K",
    "pip": 14,
    "court": true
  },
  {
    "id": "ace-of-cups",
    "name": "Ace of Cups",
    "blurb": "New love, compassion, and the overflow of emotional or spiritual gifts. The Ace of Cups opens the heart to something fresh.",
    "upright": "new love, compassion, creativity, intuition, spiritual gifts",
    "reversed": "blocked creativity, emptiness, emotional loss, repressed feelings",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "cups",
    "index": "A",
    "pip": 1,
    "court": false
  },
  {
    "id": "two-of-cups",
    "name": "Two of Cups",
    "blurb": "Partnership, mutual attraction, and a deep connection between two people. The Two of Cups signals love or alliance.",
    "upright": "partnership, union, attraction, connection, proposal",
    "reversed": "imbalanced relationship, broken communication, separation, tension",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "cups",
    "index": "2",
    "pip": 2,
    "court": false
  },
  {
    "id": "three-of-cups",
    "name": "Three of Cups",
    "blurb": "Celebration, friendship, and the joy of community. The Three of Cups raises a glass to the people who matter most.",
    "upright": "celebration, friendship, creativity, community, abundance",
    "reversed": "independence, alone time, over-indulgence, gossip, group tension",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "cups",
    "index": "3",
    "pip": 3,
    "court": false
  },
  {
    "id": "four-of-cups",
    "name": "Four of Cups",
    "blurb": "Apathy, boredom, and missing an opportunity because you are too lost in thought. The Four of Cups says look up.",
    "upright": "apathy, contemplation, withdrawn, reevaluation, boredom",
    "reversed": "retreat, avoiding others, excessive contemplation, missing opportunity",
    "yesNo": "No",
    "arcana": "minor",
    "suit": "cups",
    "index": "4",
    "pip": 4,
    "court": false
  },
  {
    "id": "five-of-cups",
    "name": "Five of Cups",
    "blurb": "Grief, regret, and focusing on what was lost. The Five of Cups reminds you that two cups still stand behind you.",
    "upright": "regret, loss, grief, disappointment, dwelling on the past",
    "reversed": "moving on, acceptance, forgiveness, letting go, finding peace",
    "yesNo": "No",
    "arcana": "minor",
    "suit": "cups",
    "index": "5",
    "pip": 5,
    "court": false
  },
  {
    "id": "six-of-cups",
    "name": "Six of Cups",
    "blurb": "Nostalgia, childhood memories, and the sweetness of looking back. The Six of Cups connects you to innocence and giving.",
    "upright": "nostalgia, childhood memories, innocence, giving, past connections",
    "reversed": "stuck in the past, naivety, unrealistic, moving forward, leaving home",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "cups",
    "index": "6",
    "pip": 6,
    "court": false
  },
  {
    "id": "seven-of-cups",
    "name": "Seven of Cups",
    "blurb": "Fantasy, illusion, and too many choices. The Seven of Cups warns that not every shining option is real.",
    "upright": "choices, fantasy, illusion, wishful thinking, temptation",
    "reversed": "alignment, clarity, making choices, disillusioned, temptation",
    "yesNo": "Maybe",
    "arcana": "minor",
    "suit": "cups",
    "index": "7",
    "pip": 7,
    "court": false
  },
  {
    "id": "eight-of-cups",
    "name": "Eight of Cups",
    "blurb": "Walking away from something that no longer fulfills you. The Eight of Cups chooses growth over comfort.",
    "upright": "disappointment, abandonment, withdrawal, escapism, walking away",
    "reversed": "fearing change, drifting, trying again, staying in a bad situation",
    "yesNo": "No",
    "arcana": "minor",
    "suit": "cups",
    "index": "8",
    "pip": 8,
    "court": false
  },
  {
    "id": "nine-of-cups",
    "name": "Nine of Cups",
    "blurb": "Contentment, satisfaction, and wishes fulfilled. The Nine of Cups is the wish card -- enjoy what you have earned.",
    "upright": "contentment, satisfaction, gratitude, wish card, emotional fulfillment",
    "reversed": "lack of fulfilment, materialism, complacency, overindulgence",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "cups",
    "index": "9",
    "pip": 9,
    "court": false
  },
  {
    "id": "ten-of-cups",
    "name": "Ten of Cups",
    "blurb": "Emotional fulfillment, family harmony, and lasting happiness. The Ten of Cups is the happiest card in the deck.",
    "upright": "divine love, blissful relationships, harmony, family, happy home",
    "reversed": "broken home, conflict, misaligned values, seeking happiness outside",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "cups",
    "index": "10",
    "pip": 10,
    "court": false
  },
  {
    "id": "page-of-cups",
    "name": "Page of Cups",
    "blurb": "Creative messages, intuitive feelings, and the wonder of the inner child. The Page of Cups brings unexpected emotional news.",
    "upright": "emotional messages, creative, intuitive, inner child, unexpected news",
    "reversed": "emotional immaturity, insecurity, repressing emotions, creative blocks",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "cups",
    "index": "P",
    "pip": 11,
    "court": true
  },
  {
    "id": "knight-of-cups",
    "name": "Knight of Cups",
    "blurb": "Romance, charm, and following your heart wherever it leads. The Knight of Cups is the dreamer who acts on feeling.",
    "upright": "romance, charm, imagination, sensitivity, idealism",
    "reversed": "moodiness, disappointment, jealousy, unrealistic, escapism",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "cups",
    "index": "Kn",
    "pip": 12,
    "court": true
  },
  {
    "id": "queen-of-cups",
    "name": "Queen of Cups",
    "blurb": "Compassion, emotional security, and deep intuitive wisdom. The Queen of Cups nurtures others without losing herself.",
    "upright": "compassion, nurturing, empathy, emotional security, intuition",
    "reversed": "inner feelings neglected, codependency, emotional insecurity, manipulation",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "cups",
    "index": "Q",
    "pip": 13,
    "court": true
  },
  {
    "id": "king-of-cups",
    "name": "King of Cups",
    "blurb": "Emotional balance, diplomacy, and the calm strength of someone who has mastered their feelings.",
    "upright": "emotionally balanced, compassionate, diplomatic, wisdom, calmness",
    "reversed": "emotional manipulation, volatility, moodiness, repression, coldness",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "cups",
    "index": "K",
    "pip": 14,
    "court": true
  },
  {
    "id": "ace-of-swords",
    "name": "Ace of Swords",
    "blurb": "Clarity, breakthrough, and a powerful new idea cutting through confusion. The Ace of Swords is truth revealed.",
    "upright": "clarity, breakthrough, new ideas, truth, mental force",
    "reversed": "confusion, chaos, miscommunication, lack of clarity, false beliefs",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "swords",
    "index": "A",
    "pip": 1,
    "court": false
  },
  {
    "id": "two-of-swords",
    "name": "Two of Swords",
    "blurb": "Indecision, stalemate, and the discomfort of avoiding a difficult choice. The Two of Swords asks you to open your eyes.",
    "upright": "indecision, stalemate, blocked emotions, avoidance, difficult choices",
    "reversed": "indecision, confusion, information overload, no right choice",
    "yesNo": "No",
    "arcana": "minor",
    "suit": "swords",
    "index": "2",
    "pip": 2,
    "court": false
  },
  {
    "id": "three-of-swords",
    "name": "Three of Swords",
    "blurb": "Heartbreak, sorrow, and the pain that comes when truth hurts. The Three of Swords says grief is part of healing.",
    "upright": "heartbreak, sorrow, grief, loss, emotional pain",
    "reversed": "healing, forgiveness, recovering from hurt, releasing pain, moving on",
    "yesNo": "No",
    "arcana": "minor",
    "suit": "swords",
    "index": "3",
    "pip": 3,
    "court": false
  },
  {
    "id": "four-of-swords",
    "name": "Four of Swords",
    "blurb": "Rest, recovery, and the wisdom of stepping back before you burn out. The Four of Swords prescribes stillness.",
    "upright": "rest, recovery, contemplation, peace, sanctuary",
    "reversed": "restlessness, burnout, re-entering the world, exhaustion, anxiety",
    "yesNo": "Maybe",
    "arcana": "minor",
    "suit": "swords",
    "index": "4",
    "pip": 4,
    "court": false
  },
  {
    "id": "five-of-swords",
    "name": "Five of Swords",
    "blurb": "Conflict, defeat, and the hollow feeling of winning at someone else's expense. The Five of Swords asks: was it worth it?",
    "upright": "conflict, disagreement, defeat, bullying, hollow victory",
    "reversed": "reconciliation, moving past conflict, forgiveness, regret",
    "yesNo": "No",
    "arcana": "minor",
    "suit": "swords",
    "index": "5",
    "pip": 5,
    "court": false
  },
  {
    "id": "six-of-swords",
    "name": "Six of Swords",
    "blurb": "Transition, moving on, and leaving difficulty behind. The Six of Swords carries you toward calmer water.",
    "upright": "transition, change, moving on, rite of passage, releasing baggage",
    "reversed": "emotional baggage, resisting transition, returning to difficulty, unfinished",
    "yesNo": "Maybe",
    "arcana": "minor",
    "suit": "swords",
    "index": "6",
    "pip": 6,
    "court": false
  },
  {
    "id": "seven-of-swords",
    "name": "Seven of Swords",
    "blurb": "Deception, strategy, and the risk of trying to get away with something. The Seven of Swords warns: shortcuts have costs.",
    "upright": "deception, betrayal, strategy, cunning, getting away with something",
    "reversed": "coming clean, confessing, self-deception, exposure",
    "yesNo": "No",
    "arcana": "minor",
    "suit": "swords",
    "index": "7",
    "pip": 7,
    "court": false
  },
  {
    "id": "eight-of-swords",
    "name": "Eight of Swords",
    "blurb": "Feeling trapped, restricted, and powerless -- but the bindings are often self-imposed. The Eight of Swords says the exit exists.",
    "upright": "imprisonment, restriction, self-victimization, helplessness, trapped",
    "reversed": "releasing restrictions, mental freedom, facing fears, moving forward",
    "yesNo": "No",
    "arcana": "minor",
    "suit": "swords",
    "index": "8",
    "pip": 8,
    "court": false
  },
  {
    "id": "nine-of-swords",
    "name": "Nine of Swords",
    "blurb": "Anxiety, worry, and the nightmares that come from overthinking. The Nine of Swords says the fear is worse than the reality.",
    "upright": "anxiety, worry, fear, nightmares, despair",
    "reversed": "inner turmoil, releasing anxiety, coming to terms with fears, recovery",
    "yesNo": "No",
    "arcana": "minor",
    "suit": "swords",
    "index": "9",
    "pip": 9,
    "court": false
  },
  {
    "id": "ten-of-swords",
    "name": "Ten of Swords",
    "blurb": "Painful endings, betrayal, and hitting rock bottom. The Ten of Swords says it cannot get worse -- which means it gets better.",
    "upright": "painful endings, loss, betrayal, rock bottom, crisis",
    "reversed": "recovery, regeneration, fear of ruin, inevitable end, surviving",
    "yesNo": "No",
    "arcana": "minor",
    "suit": "swords",
    "index": "10",
    "pip": 10,
    "court": false
  },
  {
    "id": "page-of-swords",
    "name": "Page of Swords",
    "blurb": "Curiosity, mental energy, and the sharp questioning of someone learning to think critically.",
    "upright": "curiosity, restlessness, mental energy, inquisitiveness, chatterbox",
    "reversed": "deceptive, manipulative, all talk, cynicism, haste",
    "yesNo": "Maybe",
    "arcana": "minor",
    "suit": "swords",
    "index": "P",
    "pip": 11,
    "court": true
  },
  {
    "id": "knight-of-swords",
    "name": "Knight of Swords",
    "blurb": "Ambition, fast action, and the drive to charge ahead without always thinking things through.",
    "upright": "ambitious, action-oriented, fast-thinking, assertive, competitive",
    "reversed": "impulsive, reckless, argumentative, rushing, know-it-all",
    "yesNo": "Maybe",
    "arcana": "minor",
    "suit": "swords",
    "index": "Kn",
    "pip": 12,
    "court": true
  },
  {
    "id": "queen-of-swords",
    "name": "Queen of Swords",
    "blurb": "Clear boundaries, honesty, and the independence of someone who trusts their own perception above all else.",
    "upright": "clear boundaries, honest, direct, independent, perception",
    "reversed": "cold-hearted, bitter, cruel, resentful, overly critical",
    "yesNo": "Maybe",
    "arcana": "minor",
    "suit": "swords",
    "index": "Q",
    "pip": 13,
    "court": true
  },
  {
    "id": "king-of-swords",
    "name": "King of Swords",
    "blurb": "Authority, intellectual clarity, and the ethical use of power. The King of Swords rules with truth, not force.",
    "upright": "authority, clarity, truth, decisiveness, ethics",
    "reversed": "misuse of power, manipulative, tyrannical, cold, ruthless",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "swords",
    "index": "K",
    "pip": 14,
    "court": true
  },
  {
    "id": "ace-of-pentacles",
    "name": "Ace of Pentacles",
    "blurb": "A new financial opportunity or the seed of material abundance. The Ace of Pentacles says the foundation is ready to build.",
    "upright": "new financial opportunity, abundance, prosperity, stability, manifestation",
    "reversed": "missed opportunity, bad investments, financial loss, scarcity",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "pentacles",
    "index": "A",
    "pip": 1,
    "court": false
  },
  {
    "id": "two-of-pentacles",
    "name": "Two of Pentacles",
    "blurb": "Balance, adaptability, and juggling competing priorities. The Two of Pentacles asks: what deserves your attention right now?",
    "upright": "balance, adaptability, time management, juggling priorities, flexibility",
    "reversed": "imbalance, disorganization, overwhelmed, financial mismanagement",
    "yesNo": "Maybe",
    "arcana": "minor",
    "suit": "pentacles",
    "index": "2",
    "pip": 2,
    "court": false
  },
  {
    "id": "three-of-pentacles",
    "name": "Three of Pentacles",
    "blurb": "Teamwork, skill building, and the progress that comes from collaboration. The Three of Pentacles values craft over speed.",
    "upright": "teamwork, collaboration, skill building, commitment, mastery",
    "reversed": "disharmony in teams, poor planning, working alone, lack of cohesion",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "pentacles",
    "index": "3",
    "pip": 3,
    "court": false
  },
  {
    "id": "four-of-pentacles",
    "name": "Four of Pentacles",
    "blurb": "Security, control, and the tension between saving and holding too tight. The Four of Pentacles asks what you are afraid to lose.",
    "upright": "saving money, security, conservatism, scarcity, control",
    "reversed": "over-spending, greediness, self-protection, materialism, letting go",
    "yesNo": "Maybe",
    "arcana": "minor",
    "suit": "pentacles",
    "index": "4",
    "pip": 4,
    "court": false
  },
  {
    "id": "five-of-pentacles",
    "name": "Five of Pentacles",
    "blurb": "Financial loss, hardship, and the isolation of struggling alone. The Five of Pentacles says help is closer than it looks.",
    "upright": "financial loss, poverty, lack, isolation, adversity",
    "reversed": "recovery from financial loss, spiritual poverty, isolation ending",
    "yesNo": "No",
    "arcana": "minor",
    "suit": "pentacles",
    "index": "5",
    "pip": 5,
    "court": false
  },
  {
    "id": "six-of-pentacles",
    "name": "Six of Pentacles",
    "blurb": "Generosity, giving and receiving, and the flow of resources between people. The Six of Pentacles asks: which side are you on?",
    "upright": "generosity, charity, giving, taking, prosperity sharing",
    "reversed": "selfishness, debt, one-sided charity, strings attached, power imbalance",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "pentacles",
    "index": "6",
    "pip": 6,
    "court": false
  },
  {
    "id": "seven-of-pentacles",
    "name": "Seven of Pentacles",
    "blurb": "Patience, long-term investment, and the waiting that comes before harvest. The Seven of Pentacles says keep going.",
    "upright": "long-term view, sustainable results, perseverance, investment, patience",
    "reversed": "lack of long-term vision, limited success, procrastination, no reward",
    "yesNo": "Maybe",
    "arcana": "minor",
    "suit": "pentacles",
    "index": "7",
    "pip": 7,
    "court": false
  },
  {
    "id": "eight-of-pentacles",
    "name": "Eight of Pentacles",
    "blurb": "Diligence, craftsmanship, and the quiet dedication of mastering a skill through repetition.",
    "upright": "diligence, knowledge, craftsmanship, skill development, dedication",
    "reversed": "self-development, perfectionism, boredom, lack of focus, bad work",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "pentacles",
    "index": "8",
    "pip": 8,
    "court": false
  },
  {
    "id": "nine-of-pentacles",
    "name": "Nine of Pentacles",
    "blurb": "Abundance, self-sufficiency, and the luxury of having built something entirely your own.",
    "upright": "abundance, luxury, self-sufficiency, financial independence, gratitude",
    "reversed": "financial dependency, overinvestment in work, gold-digging, hustling",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "pentacles",
    "index": "9",
    "pip": 9,
    "court": false
  },
  {
    "id": "ten-of-pentacles",
    "name": "Ten of Pentacles",
    "blurb": "Legacy, family wealth, and the security of something built to last beyond one lifetime.",
    "upright": "legacy, culmination, family, wealth, lasting success",
    "reversed": "failing family structures, financial failure, loss of legacy, instability",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "pentacles",
    "index": "10",
    "pip": 10,
    "court": false
  },
  {
    "id": "page-of-pentacles",
    "name": "Page of Pentacles",
    "blurb": "Ambition, new skills, and the eagerness to learn something practical. The Page of Pentacles is a diligent student.",
    "upright": "ambition, diligence, manifestation, financial opportunity, new skills",
    "reversed": "procrastination, lack of progress, underachieving, short-term thinking",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "pentacles",
    "index": "P",
    "pip": 11,
    "court": true
  },
  {
    "id": "knight-of-pentacles",
    "name": "Knight of Pentacles",
    "blurb": "Reliability, routine, and steady progress through hard work. The Knight of Pentacles is slow but never quits.",
    "upright": "efficiency, routine, conservative, methodical, hardworking",
    "reversed": "laziness, boredom, feeling stuck, obsessiveness, perfectionism",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "pentacles",
    "index": "Kn",
    "pip": 12,
    "court": true
  },
  {
    "id": "queen-of-pentacles",
    "name": "Queen of Pentacles",
    "blurb": "Practical nurturing, financial security, and the warmth of a well-kept home. The Queen of Pentacles makes abundance feel natural.",
    "upright": "practical, homebody, motherly, down-to-earth, financial security",
    "reversed": "financial dependency, work-family imbalance, smothering, jealousy",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "pentacles",
    "index": "Q",
    "pip": 13,
    "court": true
  },
  {
    "id": "king-of-pentacles",
    "name": "King of Pentacles",
    "blurb": "Prosperity, discipline, and the quiet confidence of someone who built their wealth through patience and strategy.",
    "upright": "abundance, prosperity, security, ambition, discipline",
    "reversed": "corruption, greed, over-indulgence, exploitation, financial failure",
    "yesNo": "Yes",
    "arcana": "minor",
    "suit": "pentacles",
    "index": "K",
    "pip": 14,
    "court": true
  }
];

export const SUIT_ELEMENT: Record<Suit, "fire" | "water" | "air" | "earth"> = {
  wands: "fire",
  cups: "water",
  swords: "air",
  pentacles: "earth",
};

